package r4

import "time"

//generated with command go run ./bultaoreune
//inputs https://www.hl7.org/fhir/r4/[profiles-resources.json profiles-types.json valuesets.json]
//for details see https://github.com/PotatoEMR/simple-fhir-client

// http://hl7.org/fhir/r4/StructureDefinition/ElementDefinition
type ElementDefinition struct {
	Id                              *string              `json:"id,omitempty"`
	Extension                       []Extension          `json:"extension,omitempty"`
	ModifierExtension               []Extension          `json:"modifierExtension,omitempty"`
	Path                            string               `json:"path"`
	Representation                  []string             `json:"representation,omitempty"`
	SliceName                       *string              `json:"sliceName,omitempty"`
	SliceIsConstraining             *bool                `json:"sliceIsConstraining,omitempty"`
	Label                           *string              `json:"label,omitempty"`
	Code                            []Coding             `json:"code,omitempty"`
	Slicing                         *Element             `json:"slicing,omitempty"`
	Short                           *string              `json:"short,omitempty"`
	Definition                      *string              `json:"definition,omitempty"`
	Comment                         *string              `json:"comment,omitempty"`
	Requirements                    *string              `json:"requirements,omitempty"`
	Alias                           []string             `json:"alias,omitempty"`
	Min                             *int                 `json:"min,omitempty"`
	Max                             *string              `json:"max,omitempty"`
	Base                            *Element             `json:"base,omitempty"`
	ContentReference                *string              `json:"contentReference,omitempty"`
	Type                            []Element            `json:"type,omitempty"`
	DefaultValueBase64Binary        *string              `json:"defaultValueBase64Binary,omitempty"`
	DefaultValueBoolean             *bool                `json:"defaultValueBoolean,omitempty"`
	DefaultValueCanonical           *string              `json:"defaultValueCanonical,omitempty"`
	DefaultValueCode                *string              `json:"defaultValueCode,omitempty"`
	DefaultValueDate                *time.Time           `json:"defaultValueDate,omitempty,format:'2006-01-02'"`
	DefaultValueDateTime            *time.Time           `json:"defaultValueDateTime,omitempty,format:'2006-01-02T15:04:05Z07:00'"`
	DefaultValueDecimal             *float64             `json:"defaultValueDecimal,omitempty"`
	DefaultValueId                  *string              `json:"defaultValueId,omitempty"`
	DefaultValueInstant             *string              `json:"defaultValueInstant,omitempty"`
	DefaultValueInteger             *int                 `json:"defaultValueInteger,omitempty"`
	DefaultValueMarkdown            *string              `json:"defaultValueMarkdown,omitempty"`
	DefaultValueOid                 *string              `json:"defaultValueOid,omitempty"`
	DefaultValuePositiveInt         *int                 `json:"defaultValuePositiveInt,omitempty"`
	DefaultValueString              *string              `json:"defaultValueString,omitempty"`
	DefaultValueTime                *string              `json:"defaultValueTime,omitempty"`
	DefaultValueUnsignedInt         *int                 `json:"defaultValueUnsignedInt,omitempty"`
	DefaultValueUri                 *string              `json:"defaultValueUri,omitempty"`
	DefaultValueUrl                 *string              `json:"defaultValueUrl,omitempty"`
	DefaultValueUuid                *string              `json:"defaultValueUuid,omitempty"`
	DefaultValueAddress             *Address             `json:"defaultValueAddress,omitempty"`
	DefaultValueAge                 *Age                 `json:"defaultValueAge,omitempty"`
	DefaultValueAnnotation          *Annotation          `json:"defaultValueAnnotation,omitempty"`
	DefaultValueAttachment          *Attachment          `json:"defaultValueAttachment,omitempty"`
	DefaultValueCodeableConcept     *CodeableConcept     `json:"defaultValueCodeableConcept,omitempty"`
	DefaultValueCoding              *Coding              `json:"defaultValueCoding,omitempty"`
	DefaultValueContactPoint        *ContactPoint        `json:"defaultValueContactPoint,omitempty"`
	DefaultValueCount               *Count               `json:"defaultValueCount,omitempty"`
	DefaultValueDistance            *Distance            `json:"defaultValueDistance,omitempty"`
	DefaultValueDuration            *Duration            `json:"defaultValueDuration,omitempty"`
	DefaultValueHumanName           *HumanName           `json:"defaultValueHumanName,omitempty"`
	DefaultValueIdentifier          *Identifier          `json:"defaultValueIdentifier,omitempty"`
	DefaultValueMoney               *Money               `json:"defaultValueMoney,omitempty"`
	DefaultValuePeriod              *Period              `json:"defaultValuePeriod,omitempty"`
	DefaultValueQuantity            *Quantity            `json:"defaultValueQuantity,omitempty"`
	DefaultValueRange               *Range               `json:"defaultValueRange,omitempty"`
	DefaultValueRatio               *Ratio               `json:"defaultValueRatio,omitempty"`
	DefaultValueReference           *Reference           `json:"defaultValueReference,omitempty"`
	DefaultValueSampledData         *SampledData         `json:"defaultValueSampledData,omitempty"`
	DefaultValueSignature           *Signature           `json:"defaultValueSignature,omitempty"`
	DefaultValueTiming              *Timing              `json:"defaultValueTiming,omitempty"`
	DefaultValueContactDetail       *ContactDetail       `json:"defaultValueContactDetail,omitempty"`
	DefaultValueContributor         *Contributor         `json:"defaultValueContributor,omitempty"`
	DefaultValueDataRequirement     *DataRequirement     `json:"defaultValueDataRequirement,omitempty"`
	DefaultValueExpression          *Expression          `json:"defaultValueExpression,omitempty"`
	DefaultValueParameterDefinition *ParameterDefinition `json:"defaultValueParameterDefinition,omitempty"`
	DefaultValueRelatedArtifact     *RelatedArtifact     `json:"defaultValueRelatedArtifact,omitempty"`
	DefaultValueTriggerDefinition   *TriggerDefinition   `json:"defaultValueTriggerDefinition,omitempty"`
	DefaultValueUsageContext        *UsageContext        `json:"defaultValueUsageContext,omitempty"`
	DefaultValueDosage              *Dosage              `json:"defaultValueDosage,omitempty"`
	DefaultValueMeta                *Meta                `json:"defaultValueMeta,omitempty"`
	MeaningWhenMissing              *string              `json:"meaningWhenMissing,omitempty"`
	OrderMeaning                    *string              `json:"orderMeaning,omitempty"`
	FixedBase64Binary               *string              `json:"fixedBase64Binary,omitempty"`
	FixedBoolean                    *bool                `json:"fixedBoolean,omitempty"`
	FixedCanonical                  *string              `json:"fixedCanonical,omitempty"`
	FixedCode                       *string              `json:"fixedCode,omitempty"`
	FixedDate                       *time.Time           `json:"fixedDate,omitempty,format:'2006-01-02'"`
	FixedDateTime                   *time.Time           `json:"fixedDateTime,omitempty,format:'2006-01-02T15:04:05Z07:00'"`
	FixedDecimal                    *float64             `json:"fixedDecimal,omitempty"`
	FixedId                         *string              `json:"fixedId,omitempty"`
	FixedInstant                    *string              `json:"fixedInstant,omitempty"`
	FixedInteger                    *int                 `json:"fixedInteger,omitempty"`
	FixedMarkdown                   *string              `json:"fixedMarkdown,omitempty"`
	FixedOid                        *string              `json:"fixedOid,omitempty"`
	FixedPositiveInt                *int                 `json:"fixedPositiveInt,omitempty"`
	FixedString                     *string              `json:"fixedString,omitempty"`
	FixedTime                       *string              `json:"fixedTime,omitempty"`
	FixedUnsignedInt                *int                 `json:"fixedUnsignedInt,omitempty"`
	FixedUri                        *string              `json:"fixedUri,omitempty"`
	FixedUrl                        *string              `json:"fixedUrl,omitempty"`
	FixedUuid                       *string              `json:"fixedUuid,omitempty"`
	FixedAddress                    *Address             `json:"fixedAddress,omitempty"`
	FixedAge                        *Age                 `json:"fixedAge,omitempty"`
	FixedAnnotation                 *Annotation          `json:"fixedAnnotation,omitempty"`
	FixedAttachment                 *Attachment          `json:"fixedAttachment,omitempty"`
	FixedCodeableConcept            *CodeableConcept     `json:"fixedCodeableConcept,omitempty"`
	FixedCoding                     *Coding              `json:"fixedCoding,omitempty"`
	FixedContactPoint               *ContactPoint        `json:"fixedContactPoint,omitempty"`
	FixedCount                      *Count               `json:"fixedCount,omitempty"`
	FixedDistance                   *Distance            `json:"fixedDistance,omitempty"`
	FixedDuration                   *Duration            `json:"fixedDuration,omitempty"`
	FixedHumanName                  *HumanName           `json:"fixedHumanName,omitempty"`
	FixedIdentifier                 *Identifier          `json:"fixedIdentifier,omitempty"`
	FixedMoney                      *Money               `json:"fixedMoney,omitempty"`
	FixedPeriod                     *Period              `json:"fixedPeriod,omitempty"`
	FixedQuantity                   *Quantity            `json:"fixedQuantity,omitempty"`
	FixedRange                      *Range               `json:"fixedRange,omitempty"`
	FixedRatio                      *Ratio               `json:"fixedRatio,omitempty"`
	FixedReference                  *Reference           `json:"fixedReference,omitempty"`
	FixedSampledData                *SampledData         `json:"fixedSampledData,omitempty"`
	FixedSignature                  *Signature           `json:"fixedSignature,omitempty"`
	FixedTiming                     *Timing              `json:"fixedTiming,omitempty"`
	FixedContactDetail              *ContactDetail       `json:"fixedContactDetail,omitempty"`
	FixedContributor                *Contributor         `json:"fixedContributor,omitempty"`
	FixedDataRequirement            *DataRequirement     `json:"fixedDataRequirement,omitempty"`
	FixedExpression                 *Expression          `json:"fixedExpression,omitempty"`
	FixedParameterDefinition        *ParameterDefinition `json:"fixedParameterDefinition,omitempty"`
	FixedRelatedArtifact            *RelatedArtifact     `json:"fixedRelatedArtifact,omitempty"`
	FixedTriggerDefinition          *TriggerDefinition   `json:"fixedTriggerDefinition,omitempty"`
	FixedUsageContext               *UsageContext        `json:"fixedUsageContext,omitempty"`
	FixedDosage                     *Dosage              `json:"fixedDosage,omitempty"`
	FixedMeta                       *Meta                `json:"fixedMeta,omitempty"`
	PatternBase64Binary             *string              `json:"patternBase64Binary,omitempty"`
	PatternBoolean                  *bool                `json:"patternBoolean,omitempty"`
	PatternCanonical                *string              `json:"patternCanonical,omitempty"`
	PatternCode                     *string              `json:"patternCode,omitempty"`
	PatternDate                     *time.Time           `json:"patternDate,omitempty,format:'2006-01-02'"`
	PatternDateTime                 *time.Time           `json:"patternDateTime,omitempty,format:'2006-01-02T15:04:05Z07:00'"`
	PatternDecimal                  *float64             `json:"patternDecimal,omitempty"`
	PatternId                       *string              `json:"patternId,omitempty"`
	PatternInstant                  *string              `json:"patternInstant,omitempty"`
	PatternInteger                  *int                 `json:"patternInteger,omitempty"`
	PatternMarkdown                 *string              `json:"patternMarkdown,omitempty"`
	PatternOid                      *string              `json:"patternOid,omitempty"`
	PatternPositiveInt              *int                 `json:"patternPositiveInt,omitempty"`
	PatternString                   *string              `json:"patternString,omitempty"`
	PatternTime                     *string              `json:"patternTime,omitempty"`
	PatternUnsignedInt              *int                 `json:"patternUnsignedInt,omitempty"`
	PatternUri                      *string              `json:"patternUri,omitempty"`
	PatternUrl                      *string              `json:"patternUrl,omitempty"`
	PatternUuid                     *string              `json:"patternUuid,omitempty"`
	PatternAddress                  *Address             `json:"patternAddress,omitempty"`
	PatternAge                      *Age                 `json:"patternAge,omitempty"`
	PatternAnnotation               *Annotation          `json:"patternAnnotation,omitempty"`
	PatternAttachment               *Attachment          `json:"patternAttachment,omitempty"`
	PatternCodeableConcept          *CodeableConcept     `json:"patternCodeableConcept,omitempty"`
	PatternCoding                   *Coding              `json:"patternCoding,omitempty"`
	PatternContactPoint             *ContactPoint        `json:"patternContactPoint,omitempty"`
	PatternCount                    *Count               `json:"patternCount,omitempty"`
	PatternDistance                 *Distance            `json:"patternDistance,omitempty"`
	PatternDuration                 *Duration            `json:"patternDuration,omitempty"`
	PatternHumanName                *HumanName           `json:"patternHumanName,omitempty"`
	PatternIdentifier               *Identifier          `json:"patternIdentifier,omitempty"`
	PatternMoney                    *Money               `json:"patternMoney,omitempty"`
	PatternPeriod                   *Period              `json:"patternPeriod,omitempty"`
	PatternQuantity                 *Quantity            `json:"patternQuantity,omitempty"`
	PatternRange                    *Range               `json:"patternRange,omitempty"`
	PatternRatio                    *Ratio               `json:"patternRatio,omitempty"`
	PatternReference                *Reference           `json:"patternReference,omitempty"`
	PatternSampledData              *SampledData         `json:"patternSampledData,omitempty"`
	PatternSignature                *Signature           `json:"patternSignature,omitempty"`
	PatternTiming                   *Timing              `json:"patternTiming,omitempty"`
	PatternContactDetail            *ContactDetail       `json:"patternContactDetail,omitempty"`
	PatternContributor              *Contributor         `json:"patternContributor,omitempty"`
	PatternDataRequirement          *DataRequirement     `json:"patternDataRequirement,omitempty"`
	PatternExpression               *Expression          `json:"patternExpression,omitempty"`
	PatternParameterDefinition      *ParameterDefinition `json:"patternParameterDefinition,omitempty"`
	PatternRelatedArtifact          *RelatedArtifact     `json:"patternRelatedArtifact,omitempty"`
	PatternTriggerDefinition        *TriggerDefinition   `json:"patternTriggerDefinition,omitempty"`
	PatternUsageContext             *UsageContext        `json:"patternUsageContext,omitempty"`
	PatternDosage                   *Dosage              `json:"patternDosage,omitempty"`
	PatternMeta                     *Meta                `json:"patternMeta,omitempty"`
	Example                         []Element            `json:"example,omitempty"`
	MinValueDate                    *time.Time           `json:"minValueDate,omitempty,format:'2006-01-02'"`
	MinValueDateTime                *time.Time           `json:"minValueDateTime,omitempty,format:'2006-01-02T15:04:05Z07:00'"`
	MinValueInstant                 *string              `json:"minValueInstant,omitempty"`
	MinValueTime                    *string              `json:"minValueTime,omitempty"`
	MinValueDecimal                 *float64             `json:"minValueDecimal,omitempty"`
	MinValueInteger                 *int                 `json:"minValueInteger,omitempty"`
	MinValuePositiveInt             *int                 `json:"minValuePositiveInt,omitempty"`
	MinValueUnsignedInt             *int                 `json:"minValueUnsignedInt,omitempty"`
	MinValueQuantity                *Quantity            `json:"minValueQuantity,omitempty"`
	MaxValueDate                    *time.Time           `json:"maxValueDate,omitempty,format:'2006-01-02'"`
	MaxValueDateTime                *time.Time           `json:"maxValueDateTime,omitempty,format:'2006-01-02T15:04:05Z07:00'"`
	MaxValueInstant                 *string              `json:"maxValueInstant,omitempty"`
	MaxValueTime                    *string              `json:"maxValueTime,omitempty"`
	MaxValueDecimal                 *float64             `json:"maxValueDecimal,omitempty"`
	MaxValueInteger                 *int                 `json:"maxValueInteger,omitempty"`
	MaxValuePositiveInt             *int                 `json:"maxValuePositiveInt,omitempty"`
	MaxValueUnsignedInt             *int                 `json:"maxValueUnsignedInt,omitempty"`
	MaxValueQuantity                *Quantity            `json:"maxValueQuantity,omitempty"`
	MaxLength                       *int                 `json:"maxLength,omitempty"`
	Condition                       []string             `json:"condition,omitempty"`
	Constraint                      []Element            `json:"constraint,omitempty"`
	MustSupport                     *bool                `json:"mustSupport,omitempty"`
	IsModifier                      *bool                `json:"isModifier,omitempty"`
	IsModifierReason                *string              `json:"isModifierReason,omitempty"`
	IsSummary                       *bool                `json:"isSummary,omitempty"`
	Binding                         *Element             `json:"binding,omitempty"`
	Mapping                         []Element            `json:"mapping,omitempty"`
}
