//generated August 18 2025 with command go run ./bultaoreune -nodownload
//inputs https://www.hl7.org/fhir/r4/[profiles-resources.json profiles-types.json]
//for details see https://github.com/PotatoEMR/simple-fhir-client

package r4

// http://hl7.org/fhir/r4/StructureDefinition/ElementDefinition
type ElementDefinition struct {
	Id                              *string              `json:"id,omitempty"`
	Extension                       []Extension          `json:"extension,omitempty"`
	ModifierExtension               []Extension          `json:"modifierExtension,omitempty"`
	Path                            string               `json:"path"`
	Representation                  []string             `json:"representation,omitempty"`
	SliceName                       *string              `json:"sliceName,omitempty"`
	SliceIsConstraining             *bool                `json:"sliceIsConstraining,omitempty"`
	Label                           *string              `json:"label,omitempty"`
	Code                            []Coding             `json:"code,omitempty"`
	Slicing                         *Element             `json:"slicing,omitempty"`
	Short                           *string              `json:"short,omitempty"`
	Definition                      *string              `json:"definition,omitempty"`
	Comment                         *string              `json:"comment,omitempty"`
	Requirements                    *string              `json:"requirements,omitempty"`
	Alias                           []string             `json:"alias,omitempty"`
	Min                             *int                 `json:"min,omitempty"`
	Max                             *string              `json:"max,omitempty"`
	Base                            *Element             `json:"base,omitempty"`
	ContentReference                *string              `json:"contentReference,omitempty"`
	Type                            []Element            `json:"type,omitempty"`
	DefaultValueBase64Binary        *string              `json:"defaultValueBase64Binary"`
	DefaultValueBoolean             *bool                `json:"defaultValueBoolean"`
	DefaultValueCanonical           *string              `json:"defaultValueCanonical"`
	DefaultValueCode                *string              `json:"defaultValueCode"`
	DefaultValueDate                *string              `json:"defaultValueDate"`
	DefaultValueDateTime            *string              `json:"defaultValueDateTime"`
	DefaultValueDecimal             *float64             `json:"defaultValueDecimal"`
	DefaultValueId                  *string              `json:"defaultValueId"`
	DefaultValueInstant             *string              `json:"defaultValueInstant"`
	DefaultValueInteger             *int                 `json:"defaultValueInteger"`
	DefaultValueMarkdown            *string              `json:"defaultValueMarkdown"`
	DefaultValueOid                 *string              `json:"defaultValueOid"`
	DefaultValuePositiveInt         *int                 `json:"defaultValuePositiveInt"`
	DefaultValueString              *string              `json:"defaultValueString"`
	DefaultValueTime                *string              `json:"defaultValueTime"`
	DefaultValueUnsignedInt         *int                 `json:"defaultValueUnsignedInt"`
	DefaultValueUri                 *string              `json:"defaultValueUri"`
	DefaultValueUrl                 *string              `json:"defaultValueUrl"`
	DefaultValueUuid                *string              `json:"defaultValueUuid"`
	DefaultValueAddress             *Address             `json:"defaultValueAddress"`
	DefaultValueAge                 *Age                 `json:"defaultValueAge"`
	DefaultValueAnnotation          *Annotation          `json:"defaultValueAnnotation"`
	DefaultValueAttachment          *Attachment          `json:"defaultValueAttachment"`
	DefaultValueCodeableConcept     *CodeableConcept     `json:"defaultValueCodeableConcept"`
	DefaultValueCoding              *Coding              `json:"defaultValueCoding"`
	DefaultValueContactPoint        *ContactPoint        `json:"defaultValueContactPoint"`
	DefaultValueCount               *Count               `json:"defaultValueCount"`
	DefaultValueDistance            *Distance            `json:"defaultValueDistance"`
	DefaultValueDuration            *Duration            `json:"defaultValueDuration"`
	DefaultValueHumanName           *HumanName           `json:"defaultValueHumanName"`
	DefaultValueIdentifier          *Identifier          `json:"defaultValueIdentifier"`
	DefaultValueMoney               *Money               `json:"defaultValueMoney"`
	DefaultValuePeriod              *Period              `json:"defaultValuePeriod"`
	DefaultValueQuantity            *Quantity            `json:"defaultValueQuantity"`
	DefaultValueRange               *Range               `json:"defaultValueRange"`
	DefaultValueRatio               *Ratio               `json:"defaultValueRatio"`
	DefaultValueReference           *Reference           `json:"defaultValueReference"`
	DefaultValueSampledData         *SampledData         `json:"defaultValueSampledData"`
	DefaultValueSignature           *Signature           `json:"defaultValueSignature"`
	DefaultValueTiming              *Timing              `json:"defaultValueTiming"`
	DefaultValueContactDetail       *ContactDetail       `json:"defaultValueContactDetail"`
	DefaultValueContributor         *Contributor         `json:"defaultValueContributor"`
	DefaultValueDataRequirement     *DataRequirement     `json:"defaultValueDataRequirement"`
	DefaultValueExpression          *Expression          `json:"defaultValueExpression"`
	DefaultValueParameterDefinition *ParameterDefinition `json:"defaultValueParameterDefinition"`
	DefaultValueRelatedArtifact     *RelatedArtifact     `json:"defaultValueRelatedArtifact"`
	DefaultValueTriggerDefinition   *TriggerDefinition   `json:"defaultValueTriggerDefinition"`
	DefaultValueUsageContext        *UsageContext        `json:"defaultValueUsageContext"`
	DefaultValueDosage              *Dosage              `json:"defaultValueDosage"`
	DefaultValueMeta                *Meta                `json:"defaultValueMeta"`
	MeaningWhenMissing              *string              `json:"meaningWhenMissing,omitempty"`
	OrderMeaning                    *string              `json:"orderMeaning,omitempty"`
	FixedBase64Binary               *string              `json:"fixedBase64Binary"`
	FixedBoolean                    *bool                `json:"fixedBoolean"`
	FixedCanonical                  *string              `json:"fixedCanonical"`
	FixedCode                       *string              `json:"fixedCode"`
	FixedDate                       *string              `json:"fixedDate"`
	FixedDateTime                   *string              `json:"fixedDateTime"`
	FixedDecimal                    *float64             `json:"fixedDecimal"`
	FixedId                         *string              `json:"fixedId"`
	FixedInstant                    *string              `json:"fixedInstant"`
	FixedInteger                    *int                 `json:"fixedInteger"`
	FixedMarkdown                   *string              `json:"fixedMarkdown"`
	FixedOid                        *string              `json:"fixedOid"`
	FixedPositiveInt                *int                 `json:"fixedPositiveInt"`
	FixedString                     *string              `json:"fixedString"`
	FixedTime                       *string              `json:"fixedTime"`
	FixedUnsignedInt                *int                 `json:"fixedUnsignedInt"`
	FixedUri                        *string              `json:"fixedUri"`
	FixedUrl                        *string              `json:"fixedUrl"`
	FixedUuid                       *string              `json:"fixedUuid"`
	FixedAddress                    *Address             `json:"fixedAddress"`
	FixedAge                        *Age                 `json:"fixedAge"`
	FixedAnnotation                 *Annotation          `json:"fixedAnnotation"`
	FixedAttachment                 *Attachment          `json:"fixedAttachment"`
	FixedCodeableConcept            *CodeableConcept     `json:"fixedCodeableConcept"`
	FixedCoding                     *Coding              `json:"fixedCoding"`
	FixedContactPoint               *ContactPoint        `json:"fixedContactPoint"`
	FixedCount                      *Count               `json:"fixedCount"`
	FixedDistance                   *Distance            `json:"fixedDistance"`
	FixedDuration                   *Duration            `json:"fixedDuration"`
	FixedHumanName                  *HumanName           `json:"fixedHumanName"`
	FixedIdentifier                 *Identifier          `json:"fixedIdentifier"`
	FixedMoney                      *Money               `json:"fixedMoney"`
	FixedPeriod                     *Period              `json:"fixedPeriod"`
	FixedQuantity                   *Quantity            `json:"fixedQuantity"`
	FixedRange                      *Range               `json:"fixedRange"`
	FixedRatio                      *Ratio               `json:"fixedRatio"`
	FixedReference                  *Reference           `json:"fixedReference"`
	FixedSampledData                *SampledData         `json:"fixedSampledData"`
	FixedSignature                  *Signature           `json:"fixedSignature"`
	FixedTiming                     *Timing              `json:"fixedTiming"`
	FixedContactDetail              *ContactDetail       `json:"fixedContactDetail"`
	FixedContributor                *Contributor         `json:"fixedContributor"`
	FixedDataRequirement            *DataRequirement     `json:"fixedDataRequirement"`
	FixedExpression                 *Expression          `json:"fixedExpression"`
	FixedParameterDefinition        *ParameterDefinition `json:"fixedParameterDefinition"`
	FixedRelatedArtifact            *RelatedArtifact     `json:"fixedRelatedArtifact"`
	FixedTriggerDefinition          *TriggerDefinition   `json:"fixedTriggerDefinition"`
	FixedUsageContext               *UsageContext        `json:"fixedUsageContext"`
	FixedDosage                     *Dosage              `json:"fixedDosage"`
	FixedMeta                       *Meta                `json:"fixedMeta"`
	PatternBase64Binary             *string              `json:"patternBase64Binary"`
	PatternBoolean                  *bool                `json:"patternBoolean"`
	PatternCanonical                *string              `json:"patternCanonical"`
	PatternCode                     *string              `json:"patternCode"`
	PatternDate                     *string              `json:"patternDate"`
	PatternDateTime                 *string              `json:"patternDateTime"`
	PatternDecimal                  *float64             `json:"patternDecimal"`
	PatternId                       *string              `json:"patternId"`
	PatternInstant                  *string              `json:"patternInstant"`
	PatternInteger                  *int                 `json:"patternInteger"`
	PatternMarkdown                 *string              `json:"patternMarkdown"`
	PatternOid                      *string              `json:"patternOid"`
	PatternPositiveInt              *int                 `json:"patternPositiveInt"`
	PatternString                   *string              `json:"patternString"`
	PatternTime                     *string              `json:"patternTime"`
	PatternUnsignedInt              *int                 `json:"patternUnsignedInt"`
	PatternUri                      *string              `json:"patternUri"`
	PatternUrl                      *string              `json:"patternUrl"`
	PatternUuid                     *string              `json:"patternUuid"`
	PatternAddress                  *Address             `json:"patternAddress"`
	PatternAge                      *Age                 `json:"patternAge"`
	PatternAnnotation               *Annotation          `json:"patternAnnotation"`
	PatternAttachment               *Attachment          `json:"patternAttachment"`
	PatternCodeableConcept          *CodeableConcept     `json:"patternCodeableConcept"`
	PatternCoding                   *Coding              `json:"patternCoding"`
	PatternContactPoint             *ContactPoint        `json:"patternContactPoint"`
	PatternCount                    *Count               `json:"patternCount"`
	PatternDistance                 *Distance            `json:"patternDistance"`
	PatternDuration                 *Duration            `json:"patternDuration"`
	PatternHumanName                *HumanName           `json:"patternHumanName"`
	PatternIdentifier               *Identifier          `json:"patternIdentifier"`
	PatternMoney                    *Money               `json:"patternMoney"`
	PatternPeriod                   *Period              `json:"patternPeriod"`
	PatternQuantity                 *Quantity            `json:"patternQuantity"`
	PatternRange                    *Range               `json:"patternRange"`
	PatternRatio                    *Ratio               `json:"patternRatio"`
	PatternReference                *Reference           `json:"patternReference"`
	PatternSampledData              *SampledData         `json:"patternSampledData"`
	PatternSignature                *Signature           `json:"patternSignature"`
	PatternTiming                   *Timing              `json:"patternTiming"`
	PatternContactDetail            *ContactDetail       `json:"patternContactDetail"`
	PatternContributor              *Contributor         `json:"patternContributor"`
	PatternDataRequirement          *DataRequirement     `json:"patternDataRequirement"`
	PatternExpression               *Expression          `json:"patternExpression"`
	PatternParameterDefinition      *ParameterDefinition `json:"patternParameterDefinition"`
	PatternRelatedArtifact          *RelatedArtifact     `json:"patternRelatedArtifact"`
	PatternTriggerDefinition        *TriggerDefinition   `json:"patternTriggerDefinition"`
	PatternUsageContext             *UsageContext        `json:"patternUsageContext"`
	PatternDosage                   *Dosage              `json:"patternDosage"`
	PatternMeta                     *Meta                `json:"patternMeta"`
	Example                         []Element            `json:"example,omitempty"`
	MinValueDate                    *string              `json:"minValueDate"`
	MinValueDateTime                *string              `json:"minValueDateTime"`
	MinValueInstant                 *string              `json:"minValueInstant"`
	MinValueTime                    *string              `json:"minValueTime"`
	MinValueDecimal                 *float64             `json:"minValueDecimal"`
	MinValueInteger                 *int                 `json:"minValueInteger"`
	MinValuePositiveInt             *int                 `json:"minValuePositiveInt"`
	MinValueUnsignedInt             *int                 `json:"minValueUnsignedInt"`
	MinValueQuantity                *Quantity            `json:"minValueQuantity"`
	MaxValueDate                    *string              `json:"maxValueDate"`
	MaxValueDateTime                *string              `json:"maxValueDateTime"`
	MaxValueInstant                 *string              `json:"maxValueInstant"`
	MaxValueTime                    *string              `json:"maxValueTime"`
	MaxValueDecimal                 *float64             `json:"maxValueDecimal"`
	MaxValueInteger                 *int                 `json:"maxValueInteger"`
	MaxValuePositiveInt             *int                 `json:"maxValuePositiveInt"`
	MaxValueUnsignedInt             *int                 `json:"maxValueUnsignedInt"`
	MaxValueQuantity                *Quantity            `json:"maxValueQuantity"`
	MaxLength                       *int                 `json:"maxLength,omitempty"`
	Condition                       []string             `json:"condition,omitempty"`
	Constraint                      []Element            `json:"constraint,omitempty"`
	MustSupport                     *bool                `json:"mustSupport,omitempty"`
	IsModifier                      *bool                `json:"isModifier,omitempty"`
	IsModifierReason                *string              `json:"isModifierReason,omitempty"`
	IsSummary                       *bool                `json:"isSummary,omitempty"`
	Binding                         *Element             `json:"binding,omitempty"`
	Mapping                         []Element            `json:"mapping,omitempty"`
}
