package r4bClient

import r4b "github.com/PotatoEMR/simple-fhir-client/r4b"

type ResourceGroup struct {
	Account_list                        []*r4b.Account
	ActivityDefinition_list             []*r4b.ActivityDefinition
	AdministrableProductDefinition_list []*r4b.AdministrableProductDefinition
	AdverseEvent_list                   []*r4b.AdverseEvent
	AllergyIntolerance_list             []*r4b.AllergyIntolerance
	Appointment_list                    []*r4b.Appointment
	AppointmentResponse_list            []*r4b.AppointmentResponse
	AuditEvent_list                     []*r4b.AuditEvent
	Basic_list                          []*r4b.Basic
	Binary_list                         []*r4b.Binary
	BiologicallyDerivedProduct_list     []*r4b.BiologicallyDerivedProduct
	BodyStructure_list                  []*r4b.BodyStructure
	CapabilityStatement_list            []*r4b.CapabilityStatement
	CarePlan_list                       []*r4b.CarePlan
	CareTeam_list                       []*r4b.CareTeam
	CatalogEntry_list                   []*r4b.CatalogEntry
	ChargeItem_list                     []*r4b.ChargeItem
	ChargeItemDefinition_list           []*r4b.ChargeItemDefinition
	Citation_list                       []*r4b.Citation
	Claim_list                          []*r4b.Claim
	ClaimResponse_list                  []*r4b.ClaimResponse
	ClinicalImpression_list             []*r4b.ClinicalImpression
	ClinicalUseDefinition_list          []*r4b.ClinicalUseDefinition
	CodeSystem_list                     []*r4b.CodeSystem
	Communication_list                  []*r4b.Communication
	CommunicationRequest_list           []*r4b.CommunicationRequest
	CompartmentDefinition_list          []*r4b.CompartmentDefinition
	Composition_list                    []*r4b.Composition
	ConceptMap_list                     []*r4b.ConceptMap
	Condition_list                      []*r4b.Condition
	Consent_list                        []*r4b.Consent
	Contract_list                       []*r4b.Contract
	Coverage_list                       []*r4b.Coverage
	CoverageEligibilityRequest_list     []*r4b.CoverageEligibilityRequest
	CoverageEligibilityResponse_list    []*r4b.CoverageEligibilityResponse
	DetectedIssue_list                  []*r4b.DetectedIssue
	Device_list                         []*r4b.Device
	DeviceDefinition_list               []*r4b.DeviceDefinition
	DeviceMetric_list                   []*r4b.DeviceMetric
	DeviceRequest_list                  []*r4b.DeviceRequest
	DeviceUseStatement_list             []*r4b.DeviceUseStatement
	DiagnosticReport_list               []*r4b.DiagnosticReport
	DocumentManifest_list               []*r4b.DocumentManifest
	DocumentReference_list              []*r4b.DocumentReference
	Encounter_list                      []*r4b.Encounter
	Endpoint_list                       []*r4b.Endpoint
	EnrollmentRequest_list              []*r4b.EnrollmentRequest
	EnrollmentResponse_list             []*r4b.EnrollmentResponse
	EpisodeOfCare_list                  []*r4b.EpisodeOfCare
	EventDefinition_list                []*r4b.EventDefinition
	Evidence_list                       []*r4b.Evidence
	EvidenceReport_list                 []*r4b.EvidenceReport
	EvidenceVariable_list               []*r4b.EvidenceVariable
	ExampleScenario_list                []*r4b.ExampleScenario
	ExplanationOfBenefit_list           []*r4b.ExplanationOfBenefit
	FamilyMemberHistory_list            []*r4b.FamilyMemberHistory
	Flag_list                           []*r4b.Flag
	Goal_list                           []*r4b.Goal
	GraphDefinition_list                []*r4b.GraphDefinition
	Group_list                          []*r4b.Group
	GuidanceResponse_list               []*r4b.GuidanceResponse
	HealthcareService_list              []*r4b.HealthcareService
	ImagingStudy_list                   []*r4b.ImagingStudy
	Immunization_list                   []*r4b.Immunization
	ImmunizationEvaluation_list         []*r4b.ImmunizationEvaluation
	ImmunizationRecommendation_list     []*r4b.ImmunizationRecommendation
	ImplementationGuide_list            []*r4b.ImplementationGuide
	Ingredient_list                     []*r4b.Ingredient
	InsurancePlan_list                  []*r4b.InsurancePlan
	Invoice_list                        []*r4b.Invoice
	Library_list                        []*r4b.Library
	Linkage_list                        []*r4b.Linkage
	List_list                           []*r4b.List
	Location_list                       []*r4b.Location
	ManufacturedItemDefinition_list     []*r4b.ManufacturedItemDefinition
	Measure_list                        []*r4b.Measure
	MeasureReport_list                  []*r4b.MeasureReport
	Media_list                          []*r4b.Media
	Medication_list                     []*r4b.Medication
	MedicationAdministration_list       []*r4b.MedicationAdministration
	MedicationDispense_list             []*r4b.MedicationDispense
	MedicationKnowledge_list            []*r4b.MedicationKnowledge
	MedicationRequest_list              []*r4b.MedicationRequest
	MedicationStatement_list            []*r4b.MedicationStatement
	MedicinalProductDefinition_list     []*r4b.MedicinalProductDefinition
	MessageDefinition_list              []*r4b.MessageDefinition
	MessageHeader_list                  []*r4b.MessageHeader
	MolecularSequence_list              []*r4b.MolecularSequence
	NamingSystem_list                   []*r4b.NamingSystem
	NutritionOrder_list                 []*r4b.NutritionOrder
	NutritionProduct_list               []*r4b.NutritionProduct
	Observation_list                    []*r4b.Observation
	ObservationDefinition_list          []*r4b.ObservationDefinition
	OperationDefinition_list            []*r4b.OperationDefinition
	OperationOutcome_list               []*r4b.OperationOutcome
	Organization_list                   []*r4b.Organization
	OrganizationAffiliation_list        []*r4b.OrganizationAffiliation
	PackagedProductDefinition_list      []*r4b.PackagedProductDefinition
	Patient_list                        []*r4b.Patient
	PaymentNotice_list                  []*r4b.PaymentNotice
	PaymentReconciliation_list          []*r4b.PaymentReconciliation
	Person_list                         []*r4b.Person
	PlanDefinition_list                 []*r4b.PlanDefinition
	Practitioner_list                   []*r4b.Practitioner
	PractitionerRole_list               []*r4b.PractitionerRole
	Procedure_list                      []*r4b.Procedure
	Provenance_list                     []*r4b.Provenance
	Questionnaire_list                  []*r4b.Questionnaire
	QuestionnaireResponse_list          []*r4b.QuestionnaireResponse
	RegulatedAuthorization_list         []*r4b.RegulatedAuthorization
	RelatedPerson_list                  []*r4b.RelatedPerson
	RequestGroup_list                   []*r4b.RequestGroup
	ResearchDefinition_list             []*r4b.ResearchDefinition
	ResearchElementDefinition_list      []*r4b.ResearchElementDefinition
	ResearchStudy_list                  []*r4b.ResearchStudy
	ResearchSubject_list                []*r4b.ResearchSubject
	RiskAssessment_list                 []*r4b.RiskAssessment
	Schedule_list                       []*r4b.Schedule
	SearchParameter_list                []*r4b.SearchParameter
	ServiceRequest_list                 []*r4b.ServiceRequest
	Slot_list                           []*r4b.Slot
	Specimen_list                       []*r4b.Specimen
	SpecimenDefinition_list             []*r4b.SpecimenDefinition
	StructureDefinition_list            []*r4b.StructureDefinition
	StructureMap_list                   []*r4b.StructureMap
	Subscription_list                   []*r4b.Subscription
	SubscriptionStatus_list             []*r4b.SubscriptionStatus
	SubscriptionTopic_list              []*r4b.SubscriptionTopic
	Substance_list                      []*r4b.Substance
	SubstanceDefinition_list            []*r4b.SubstanceDefinition
	SupplyDelivery_list                 []*r4b.SupplyDelivery
	SupplyRequest_list                  []*r4b.SupplyRequest
	Task_list                           []*r4b.Task
	TerminologyCapabilities_list        []*r4b.TerminologyCapabilities
	TestReport_list                     []*r4b.TestReport
	TestScript_list                     []*r4b.TestScript
	ValueSet_list                       []*r4b.ValueSet
	VerificationResult_list             []*r4b.VerificationResult
	VisionPrescription_list             []*r4b.VisionPrescription
}
