package r4Client

import r4 "github.com/PotatoEMR/simple-fhir-client/r4"

type ResourceGroup struct {
	Account_list                           []*r4.Account
	ActivityDefinition_list                []*r4.ActivityDefinition
	AdverseEvent_list                      []*r4.AdverseEvent
	AllergyIntolerance_list                []*r4.AllergyIntolerance
	Appointment_list                       []*r4.Appointment
	AppointmentResponse_list               []*r4.AppointmentResponse
	AuditEvent_list                        []*r4.AuditEvent
	Basic_list                             []*r4.Basic
	Binary_list                            []*r4.Binary
	BiologicallyDerivedProduct_list        []*r4.BiologicallyDerivedProduct
	BodyStructure_list                     []*r4.BodyStructure
	CapabilityStatement_list               []*r4.CapabilityStatement
	CarePlan_list                          []*r4.CarePlan
	CareTeam_list                          []*r4.CareTeam
	CatalogEntry_list                      []*r4.CatalogEntry
	ChargeItem_list                        []*r4.ChargeItem
	ChargeItemDefinition_list              []*r4.ChargeItemDefinition
	Claim_list                             []*r4.Claim
	ClaimResponse_list                     []*r4.ClaimResponse
	ClinicalImpression_list                []*r4.ClinicalImpression
	CodeSystem_list                        []*r4.CodeSystem
	Communication_list                     []*r4.Communication
	CommunicationRequest_list              []*r4.CommunicationRequest
	CompartmentDefinition_list             []*r4.CompartmentDefinition
	Composition_list                       []*r4.Composition
	ConceptMap_list                        []*r4.ConceptMap
	Condition_list                         []*r4.Condition
	Consent_list                           []*r4.Consent
	Contract_list                          []*r4.Contract
	Coverage_list                          []*r4.Coverage
	CoverageEligibilityRequest_list        []*r4.CoverageEligibilityRequest
	CoverageEligibilityResponse_list       []*r4.CoverageEligibilityResponse
	DetectedIssue_list                     []*r4.DetectedIssue
	Device_list                            []*r4.Device
	DeviceDefinition_list                  []*r4.DeviceDefinition
	DeviceMetric_list                      []*r4.DeviceMetric
	DeviceRequest_list                     []*r4.DeviceRequest
	DeviceUseStatement_list                []*r4.DeviceUseStatement
	DiagnosticReport_list                  []*r4.DiagnosticReport
	DocumentManifest_list                  []*r4.DocumentManifest
	DocumentReference_list                 []*r4.DocumentReference
	EffectEvidenceSynthesis_list           []*r4.EffectEvidenceSynthesis
	Encounter_list                         []*r4.Encounter
	Endpoint_list                          []*r4.Endpoint
	EnrollmentRequest_list                 []*r4.EnrollmentRequest
	EnrollmentResponse_list                []*r4.EnrollmentResponse
	EpisodeOfCare_list                     []*r4.EpisodeOfCare
	EventDefinition_list                   []*r4.EventDefinition
	Evidence_list                          []*r4.Evidence
	EvidenceVariable_list                  []*r4.EvidenceVariable
	ExampleScenario_list                   []*r4.ExampleScenario
	ExplanationOfBenefit_list              []*r4.ExplanationOfBenefit
	FamilyMemberHistory_list               []*r4.FamilyMemberHistory
	Flag_list                              []*r4.Flag
	Goal_list                              []*r4.Goal
	GraphDefinition_list                   []*r4.GraphDefinition
	Group_list                             []*r4.Group
	GuidanceResponse_list                  []*r4.GuidanceResponse
	HealthcareService_list                 []*r4.HealthcareService
	ImagingStudy_list                      []*r4.ImagingStudy
	Immunization_list                      []*r4.Immunization
	ImmunizationEvaluation_list            []*r4.ImmunizationEvaluation
	ImmunizationRecommendation_list        []*r4.ImmunizationRecommendation
	ImplementationGuide_list               []*r4.ImplementationGuide
	InsurancePlan_list                     []*r4.InsurancePlan
	Invoice_list                           []*r4.Invoice
	Library_list                           []*r4.Library
	Linkage_list                           []*r4.Linkage
	List_list                              []*r4.List
	Location_list                          []*r4.Location
	Measure_list                           []*r4.Measure
	MeasureReport_list                     []*r4.MeasureReport
	Media_list                             []*r4.Media
	Medication_list                        []*r4.Medication
	MedicationAdministration_list          []*r4.MedicationAdministration
	MedicationDispense_list                []*r4.MedicationDispense
	MedicationKnowledge_list               []*r4.MedicationKnowledge
	MedicationRequest_list                 []*r4.MedicationRequest
	MedicationStatement_list               []*r4.MedicationStatement
	MedicinalProduct_list                  []*r4.MedicinalProduct
	MedicinalProductAuthorization_list     []*r4.MedicinalProductAuthorization
	MedicinalProductContraindication_list  []*r4.MedicinalProductContraindication
	MedicinalProductIndication_list        []*r4.MedicinalProductIndication
	MedicinalProductIngredient_list        []*r4.MedicinalProductIngredient
	MedicinalProductInteraction_list       []*r4.MedicinalProductInteraction
	MedicinalProductManufactured_list      []*r4.MedicinalProductManufactured
	MedicinalProductPackaged_list          []*r4.MedicinalProductPackaged
	MedicinalProductPharmaceutical_list    []*r4.MedicinalProductPharmaceutical
	MedicinalProductUndesirableEffect_list []*r4.MedicinalProductUndesirableEffect
	MessageDefinition_list                 []*r4.MessageDefinition
	MessageHeader_list                     []*r4.MessageHeader
	MolecularSequence_list                 []*r4.MolecularSequence
	NamingSystem_list                      []*r4.NamingSystem
	NutritionOrder_list                    []*r4.NutritionOrder
	Observation_list                       []*r4.Observation
	ObservationDefinition_list             []*r4.ObservationDefinition
	OperationDefinition_list               []*r4.OperationDefinition
	OperationOutcome_list                  []*r4.OperationOutcome
	Organization_list                      []*r4.Organization
	OrganizationAffiliation_list           []*r4.OrganizationAffiliation
	Patient_list                           []*r4.Patient
	PaymentNotice_list                     []*r4.PaymentNotice
	PaymentReconciliation_list             []*r4.PaymentReconciliation
	Person_list                            []*r4.Person
	PlanDefinition_list                    []*r4.PlanDefinition
	Practitioner_list                      []*r4.Practitioner
	PractitionerRole_list                  []*r4.PractitionerRole
	Procedure_list                         []*r4.Procedure
	Provenance_list                        []*r4.Provenance
	Questionnaire_list                     []*r4.Questionnaire
	QuestionnaireResponse_list             []*r4.QuestionnaireResponse
	RelatedPerson_list                     []*r4.RelatedPerson
	RequestGroup_list                      []*r4.RequestGroup
	ResearchDefinition_list                []*r4.ResearchDefinition
	ResearchElementDefinition_list         []*r4.ResearchElementDefinition
	ResearchStudy_list                     []*r4.ResearchStudy
	ResearchSubject_list                   []*r4.ResearchSubject
	RiskAssessment_list                    []*r4.RiskAssessment
	RiskEvidenceSynthesis_list             []*r4.RiskEvidenceSynthesis
	Schedule_list                          []*r4.Schedule
	SearchParameter_list                   []*r4.SearchParameter
	ServiceRequest_list                    []*r4.ServiceRequest
	Slot_list                              []*r4.Slot
	Specimen_list                          []*r4.Specimen
	SpecimenDefinition_list                []*r4.SpecimenDefinition
	StructureDefinition_list               []*r4.StructureDefinition
	StructureMap_list                      []*r4.StructureMap
	Subscription_list                      []*r4.Subscription
	Substance_list                         []*r4.Substance
	SubstanceNucleicAcid_list              []*r4.SubstanceNucleicAcid
	SubstancePolymer_list                  []*r4.SubstancePolymer
	SubstanceProtein_list                  []*r4.SubstanceProtein
	SubstanceReferenceInformation_list     []*r4.SubstanceReferenceInformation
	SubstanceSourceMaterial_list           []*r4.SubstanceSourceMaterial
	SubstanceSpecification_list            []*r4.SubstanceSpecification
	SupplyDelivery_list                    []*r4.SupplyDelivery
	SupplyRequest_list                     []*r4.SupplyRequest
	Task_list                              []*r4.Task
	TerminologyCapabilities_list           []*r4.TerminologyCapabilities
	TestReport_list                        []*r4.TestReport
	TestScript_list                        []*r4.TestScript
	ValueSet_list                          []*r4.ValueSet
	VerificationResult_list                []*r4.VerificationResult
	VisionPrescription_list                []*r4.VisionPrescription
}
