package r5Client

import r5 "github.com/PotatoEMR/simple-fhir-client/r5"

type ResourceGroup struct {
	Account_list                            []*r5.Account
	ActivityDefinition_list                 []*r5.ActivityDefinition
	ActorDefinition_list                    []*r5.ActorDefinition
	AdministrableProductDefinition_list     []*r5.AdministrableProductDefinition
	AdverseEvent_list                       []*r5.AdverseEvent
	AllergyIntolerance_list                 []*r5.AllergyIntolerance
	Appointment_list                        []*r5.Appointment
	AppointmentResponse_list                []*r5.AppointmentResponse
	ArtifactAssessment_list                 []*r5.ArtifactAssessment
	AuditEvent_list                         []*r5.AuditEvent
	Basic_list                              []*r5.Basic
	Binary_list                             []*r5.Binary
	BiologicallyDerivedProduct_list         []*r5.BiologicallyDerivedProduct
	BiologicallyDerivedProductDispense_list []*r5.BiologicallyDerivedProductDispense
	BodyStructure_list                      []*r5.BodyStructure
	CanonicalResource_list                  []*r5.CanonicalResource
	CapabilityStatement_list                []*r5.CapabilityStatement
	CarePlan_list                           []*r5.CarePlan
	CareTeam_list                           []*r5.CareTeam
	ChargeItem_list                         []*r5.ChargeItem
	ChargeItemDefinition_list               []*r5.ChargeItemDefinition
	Citation_list                           []*r5.Citation
	Claim_list                              []*r5.Claim
	ClaimResponse_list                      []*r5.ClaimResponse
	ClinicalImpression_list                 []*r5.ClinicalImpression
	ClinicalUseDefinition_list              []*r5.ClinicalUseDefinition
	CodeSystem_list                         []*r5.CodeSystem
	Communication_list                      []*r5.Communication
	CommunicationRequest_list               []*r5.CommunicationRequest
	CompartmentDefinition_list              []*r5.CompartmentDefinition
	Composition_list                        []*r5.Composition
	ConceptMap_list                         []*r5.ConceptMap
	Condition_list                          []*r5.Condition
	ConditionDefinition_list                []*r5.ConditionDefinition
	Consent_list                            []*r5.Consent
	Contract_list                           []*r5.Contract
	Coverage_list                           []*r5.Coverage
	CoverageEligibilityRequest_list         []*r5.CoverageEligibilityRequest
	CoverageEligibilityResponse_list        []*r5.CoverageEligibilityResponse
	DetectedIssue_list                      []*r5.DetectedIssue
	Device_list                             []*r5.Device
	DeviceAssociation_list                  []*r5.DeviceAssociation
	DeviceDefinition_list                   []*r5.DeviceDefinition
	DeviceDispense_list                     []*r5.DeviceDispense
	DeviceMetric_list                       []*r5.DeviceMetric
	DeviceRequest_list                      []*r5.DeviceRequest
	DeviceUsage_list                        []*r5.DeviceUsage
	DiagnosticReport_list                   []*r5.DiagnosticReport
	DocumentReference_list                  []*r5.DocumentReference
	Encounter_list                          []*r5.Encounter
	EncounterHistory_list                   []*r5.EncounterHistory
	Endpoint_list                           []*r5.Endpoint
	EnrollmentRequest_list                  []*r5.EnrollmentRequest
	EnrollmentResponse_list                 []*r5.EnrollmentResponse
	EpisodeOfCare_list                      []*r5.EpisodeOfCare
	EventDefinition_list                    []*r5.EventDefinition
	Evidence_list                           []*r5.Evidence
	EvidenceReport_list                     []*r5.EvidenceReport
	EvidenceVariable_list                   []*r5.EvidenceVariable
	ExampleScenario_list                    []*r5.ExampleScenario
	ExplanationOfBenefit_list               []*r5.ExplanationOfBenefit
	FamilyMemberHistory_list                []*r5.FamilyMemberHistory
	Flag_list                               []*r5.Flag
	FormularyItem_list                      []*r5.FormularyItem
	GenomicStudy_list                       []*r5.GenomicStudy
	Goal_list                               []*r5.Goal
	GraphDefinition_list                    []*r5.GraphDefinition
	Group_list                              []*r5.Group
	GuidanceResponse_list                   []*r5.GuidanceResponse
	HealthcareService_list                  []*r5.HealthcareService
	ImagingSelection_list                   []*r5.ImagingSelection
	ImagingStudy_list                       []*r5.ImagingStudy
	Immunization_list                       []*r5.Immunization
	ImmunizationEvaluation_list             []*r5.ImmunizationEvaluation
	ImmunizationRecommendation_list         []*r5.ImmunizationRecommendation
	ImplementationGuide_list                []*r5.ImplementationGuide
	Ingredient_list                         []*r5.Ingredient
	InsurancePlan_list                      []*r5.InsurancePlan
	InventoryItem_list                      []*r5.InventoryItem
	InventoryReport_list                    []*r5.InventoryReport
	Invoice_list                            []*r5.Invoice
	Library_list                            []*r5.Library
	Linkage_list                            []*r5.Linkage
	List_list                               []*r5.List
	Location_list                           []*r5.Location
	ManufacturedItemDefinition_list         []*r5.ManufacturedItemDefinition
	Measure_list                            []*r5.Measure
	MeasureReport_list                      []*r5.MeasureReport
	Medication_list                         []*r5.Medication
	MedicationAdministration_list           []*r5.MedicationAdministration
	MedicationDispense_list                 []*r5.MedicationDispense
	MedicationKnowledge_list                []*r5.MedicationKnowledge
	MedicationRequest_list                  []*r5.MedicationRequest
	MedicationStatement_list                []*r5.MedicationStatement
	MedicinalProductDefinition_list         []*r5.MedicinalProductDefinition
	MessageDefinition_list                  []*r5.MessageDefinition
	MessageHeader_list                      []*r5.MessageHeader
	MolecularSequence_list                  []*r5.MolecularSequence
	NamingSystem_list                       []*r5.NamingSystem
	NutritionIntake_list                    []*r5.NutritionIntake
	NutritionOrder_list                     []*r5.NutritionOrder
	NutritionProduct_list                   []*r5.NutritionProduct
	Observation_list                        []*r5.Observation
	ObservationDefinition_list              []*r5.ObservationDefinition
	OperationDefinition_list                []*r5.OperationDefinition
	OperationOutcome_list                   []*r5.OperationOutcome
	Organization_list                       []*r5.Organization
	OrganizationAffiliation_list            []*r5.OrganizationAffiliation
	PackagedProductDefinition_list          []*r5.PackagedProductDefinition
	Patient_list                            []*r5.Patient
	PaymentNotice_list                      []*r5.PaymentNotice
	PaymentReconciliation_list              []*r5.PaymentReconciliation
	Permission_list                         []*r5.Permission
	Person_list                             []*r5.Person
	PlanDefinition_list                     []*r5.PlanDefinition
	Practitioner_list                       []*r5.Practitioner
	PractitionerRole_list                   []*r5.PractitionerRole
	Procedure_list                          []*r5.Procedure
	Provenance_list                         []*r5.Provenance
	Questionnaire_list                      []*r5.Questionnaire
	QuestionnaireResponse_list              []*r5.QuestionnaireResponse
	RegulatedAuthorization_list             []*r5.RegulatedAuthorization
	RelatedPerson_list                      []*r5.RelatedPerson
	RequestOrchestration_list               []*r5.RequestOrchestration
	Requirements_list                       []*r5.Requirements
	ResearchStudy_list                      []*r5.ResearchStudy
	ResearchSubject_list                    []*r5.ResearchSubject
	RiskAssessment_list                     []*r5.RiskAssessment
	Schedule_list                           []*r5.Schedule
	SearchParameter_list                    []*r5.SearchParameter
	ServiceRequest_list                     []*r5.ServiceRequest
	Slot_list                               []*r5.Slot
	Specimen_list                           []*r5.Specimen
	SpecimenDefinition_list                 []*r5.SpecimenDefinition
	StructureDefinition_list                []*r5.StructureDefinition
	StructureMap_list                       []*r5.StructureMap
	Subscription_list                       []*r5.Subscription
	SubscriptionStatus_list                 []*r5.SubscriptionStatus
	SubscriptionTopic_list                  []*r5.SubscriptionTopic
	Substance_list                          []*r5.Substance
	SubstanceDefinition_list                []*r5.SubstanceDefinition
	SubstanceNucleicAcid_list               []*r5.SubstanceNucleicAcid
	SubstancePolymer_list                   []*r5.SubstancePolymer
	SubstanceProtein_list                   []*r5.SubstanceProtein
	SubstanceReferenceInformation_list      []*r5.SubstanceReferenceInformation
	SubstanceSourceMaterial_list            []*r5.SubstanceSourceMaterial
	SupplyDelivery_list                     []*r5.SupplyDelivery
	SupplyRequest_list                      []*r5.SupplyRequest
	Task_list                               []*r5.Task
	TerminologyCapabilities_list            []*r5.TerminologyCapabilities
	TestPlan_list                           []*r5.TestPlan
	TestReport_list                         []*r5.TestReport
	TestScript_list                         []*r5.TestScript
	Transport_list                          []*r5.Transport
	ValueSet_list                           []*r5.ValueSet
	VerificationResult_list                 []*r5.VerificationResult
	VisionPrescription_list                 []*r5.VisionPrescription
}
